import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="bg-teal-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen py-36">
        <h1 className="text-3xl font-bold text-center">
          Tunji Productions is currently
        </h1>
        <h1 className="text-3xl font-bold text-center">
          👩🏾‍💻 Under Construction 🛠
        </h1>
      </div>
    </div>
  );
};

export default Home;
