import { Grid, Typography } from "@mui/material";
import type { NextPage } from "next";

import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid item xs={12}>
        <Typography variant="h3" textAlign="center">
          Tunji Productions
        </Typography>
      </Grid>
    </>
  );
};

export default Home;
